import React, { useState } from 'react';
import { Box, Tabs, Tab, TextField, Typography, Button } from '@mui/material';
import BackgroundTab from './BackgroundTab'; 
import CharacterTab from './CharacterTab';    
import SpecialEffectsTab from './SpecialEffectsTab'; 
import { toast } from 'react-toastify';

const ArtTab = () => {
  const [subTabId, setSubTabId] = useState(0);
  const [isEditMode, setIsEditMode] = useState(false); 
  const [manualPrompt, setManualPrompt] = useState(''); 
  const [hasManualPrompt, setHasManualPrompt] = useState(false);
  const BACKGROUND_TAB = 0;
  const CHARACTER_TAB = 1;
  const SPECIAL_EFFECTS_TAB = 2;

  const handleSubTabChange = (_event: React.SyntheticEvent, newTabId: number) => {
    setSubTabId(newTabId);
  };
  
  const onReset = () => void{
    //logic to reset all the fields to default
  }
  
  const handleGenerateClick = () => {
    // Logic for the Generate button click
    toast.info('Generating artwork...');
  };

  const handleReturnClick = () => {
    // Logic for the Return button click
    toast.info('Returning to the previous step...');
  };
  
  // Prompt object state to store the values from the tabs
  const [promptValues, setPromptValues] = useState({
    backgroundDescription: '',
    backgroundType: 'Monster',  
    characterName: '',
    race: 'Human',  
    gender: 'Male', 
    age: 'Young', 
    Charactertype: 'Main',  
    appearance: '',
    tool: '',
    action: '',
    effect: ''
  });

  // Update the prompt object values when changes are made in the tabs
  const updatePromptValues = (newValues: Partial<typeof promptValues>) => {
    setPromptValues(prevValues => ({ ...prevValues, ...newValues }));
  };

  // Constructs the prompt based on the values in the object
  const autoGeneratedPrompt = `Background: ${promptValues.backgroundDescription || 'N/A'}
  Type: ${promptValues.backgroundType || 'N/A'}
  Character: ${promptValues.characterName || 'N/A'}
  Race: ${promptValues.race || 'N/A'}
  Gender: ${promptValues.gender || 'N/A'}
  Age: ${promptValues.age || 'N/A'}
  Character type: ${promptValues.Charactertype || 'N/A'}
  Appearance: ${promptValues.appearance || 'N/A'}
  Tool: ${promptValues.tool || 'N/A'}
  Action: ${promptValues.action || 'N/A'}
  Effect: ${promptValues.effect || 'N/A'}`;

  // The current prompt to display (either auto-generated or manually edited)
  const promptText = isEditMode && hasManualPrompt ? manualPrompt : autoGeneratedPrompt;

  // Toggle edit mode
  const toggleEditMode = () => {
    if (!isEditMode) {
      if (!hasManualPrompt) {
        setManualPrompt(autoGeneratedPrompt);
        setHasManualPrompt(true);
      }
    }
    setIsEditMode(!isEditMode);
  };

  return (
    <Box>
      <Tabs
        value={subTabId}
        onChange={handleSubTabChange}
        aria-label="art sub-tabs"
        sx={{ marginBottom: '1rem' }}
      >
        <Tab label="Background" />
        <Tab label="Character" />
        <Tab label="Special Effects" />
      </Tabs>

      {/* Display the relevant sub-tab */}
      <Box sx={{ display: subTabId === BACKGROUND_TAB ? 'block' : 'none' }}>
        <BackgroundTab updatePromptValues={updatePromptValues} />
      </Box>
      <Box sx={{ display: subTabId === CHARACTER_TAB ? 'block' : 'none' }}>
        <CharacterTab updatePromptValues={updatePromptValues} />
      </Box>
      <Box sx={{ display: subTabId === SPECIAL_EFFECTS_TAB ? 'block' : 'none' }}>
        <SpecialEffectsTab updatePromptValues={updatePromptValues} />
      </Box>

      {/* Edit Mode Toggle Button */}
      <Box sx={{ marginTop: '1.5rem', marginBottom: '1rem', display: 'flex', justifyContent: 'space-between' }}>
        <Typography variant="h6">Current Prompt</Typography>
        <Button onClick={toggleEditMode} variant="contained" color={isEditMode ? 'error' : 'primary'}>
          {isEditMode ? 'Edit Mode' : 'Auto generated'}
        </Button>
      </Box>

      {/* Prompt Display Box */}
      <TextField
        fullWidth
        variant="outlined"
        multiline
        minRows={4}
        value={promptText}
        placeholder="Your prompt will appear here"
        InputProps={{
          readOnly: !isEditMode,  
        }}
        onChange={isEditMode ? (e) => setManualPrompt(e.target.value) : undefined} 
      />    
      <Box sx={{ marginTop: '1rem', display: 'flex', gap: 2, marginBottom: '2rem' }}>
      <Button variant="contained" color="primary" onClick={handleGenerateClick}>
        Generate
      </Button>
      <Button variant="outlined" color="primary" onClick={handleReturnClick}>
        Return
      </Button>
      <Button variant="outlined" color="error" onClick={onReset}>
        Reset
      </Button>
      </Box>
    </Box>
    
  );
  
};

export default ArtTab;
