import React, { useState, useEffect } from 'react';
import { Box, Tabs, Tab, TextField, Typography, Button, Modal, IconButton, FormControl, Select, MenuItem, InputLabel, InputAdornment } from '@mui/material';
import BackgroundTab from './BackgroundTab';
import CharacterTab from './CharacterTab';
import SpecialEffectsTab from './SpecialEffectsTab';
import ClearIcon from '@mui/icons-material/Clear';

const ArtTab = () => {
  const [subTabId, setSubTabId] = useState(0);
  const [isEditMode, setIsEditMode] = useState(false); // State for edit mode
  const [manualPrompt, setManualPrompt] = useState(''); // State for manually edited prompt
  const [hasManualPrompt, setHasManualPrompt] = useState(false);

  const [promptValues, setPromptValues] = useState({
    backgroundDescription: '',
    backgroundType: '',
    characterName: '',
    race: '',
    gender: '',
    age: '',
    Charactertype: '',
    appearance: '',
    tool: '',
    inherited_tool: false,
    action: '',
    effect: '',
    sideCharacterName: '',
    sideCharacterRace: '',
    sideCharacterGender: '',
    sideCharacterAge: '',
    sideCharacterAppearance: '',
    sideCharacterType: '',
  });

  const updatePromptValues = (newValues: Partial<typeof promptValues>) => {
    setPromptValues(prevValues => ({ ...prevValues, ...newValues }));
  };

  // Modal State and Functions
  const [openStyleModal, setOpenStyleModal] = useState(false);

  const handleOpenStyleModal = () => setOpenStyleModal(true);
  const handleCloseStyleModal = () => setOpenStyleModal(false);

  const handleSubTabChange = (_event: React.SyntheticEvent, newTabId: number) => {
    setSubTabId(newTabId);
  };

  // Constructs the prompt
  const autoGeneratedPrompt = `Background: ${promptValues.backgroundDescription || 'N/A'}
  Type: ${promptValues.backgroundType || 'N/A'}
  Character: ${promptValues.characterName || 'N/A'}
  Race: ${promptValues.race || 'N/A'}
  Gender: ${promptValues.gender || 'N/A'}
  Age: ${promptValues.age || 'N/A'}
  Character type: ${promptValues.Charactertype || 'N/A'}
  Appearance: ${promptValues.appearance || 'N/A'}
  Tool: ${promptValues.tool || 'N/A'}
  Inherited Tool: ${promptValues.inherited_tool ? 'Yes' : 'No'} 
  Action: ${promptValues.action || 'N/A'}
  Effect: ${promptValues.effect || 'N/A'}
  Side Character: ${promptValues.sideCharacterName || 'N/A'}
  Side Character Race: ${promptValues.sideCharacterRace || 'N/A'}
  Side Character Gender: ${promptValues.sideCharacterGender || 'N/A'}
  Side Character Age: ${promptValues.sideCharacterAge || 'N/A'}
  Side Character Appearance: ${promptValues.sideCharacterAppearance || 'N/A'}
  Side Character Type: ${promptValues.sideCharacterType || 'N/A'}`;

  // The current prompt to display (either auto-generated or manually edited)
  const promptText = isEditMode && hasManualPrompt ? manualPrompt : autoGeneratedPrompt;

  // Toggle edit mode
  const toggleEditMode = () => {
    if (!isEditMode) {
      if (!hasManualPrompt) {
        setManualPrompt(autoGeneratedPrompt);
        setHasManualPrompt(true); 
      }
    }
    setIsEditMode(!isEditMode);
  };

  return (
    <Box>
      <Tabs
        value={subTabId}
        onChange={handleSubTabChange}
        aria-label="art sub-tabs"
        sx={{ marginBottom: '1rem' }}
      >
        <Tab label="Background" />
        <Tab label="Character" />
        <Tab label="Special Effects" />
      </Tabs>

      {/* Display the relevant sub-tab */}
      <Box sx={{ display: subTabId === 0 ? 'block' : 'none' }}>
        <BackgroundTab updatePromptValues={updatePromptValues} />
      </Box>
      <Box sx={{ display: subTabId === 1 ? 'block' : 'none' }}>
        <CharacterTab updatePromptValues={updatePromptValues} />
      </Box>
      <Box sx={{ display: subTabId === 2 ? 'block' : 'none' }}>
        <SpecialEffectsTab updatePromptValues={updatePromptValues} />
      </Box>

      {/* Style Modal Button */}
      <Button variant="contained" onClick={handleOpenStyleModal}>
        Add New Style
      </Button>

      {/* Modal for Styles */}
      <Modal open={openStyleModal} onClose={handleCloseStyleModal}>
        <Box sx={{ padding: 4, backgroundColor: 'white', margin: 'auto', maxWidth: '500px' }}>
          <Typography variant="h6">Create or Edit Style</Typography>
          {/* Additional form fields for Style creation to be implemented later */}
          <Button onClick={handleCloseStyleModal}>Close</Button>
        </Box>
      </Modal>

      {/* Edit Mode Toggle Button */}
      <Box sx={{ marginTop: '1.5rem', marginBottom: '1rem', display: 'flex', justifyContent: 'space-between' }}>
        <Typography variant="h6">Current Prompt</Typography>
        <Button onClick={toggleEditMode} variant="contained" color={isEditMode ? 'error' : 'primary'}>
          {isEditMode ? 'Edit Mode' : 'Auto generated'}
        </Button>
      </Box>

      {/* Prompt Display Box */}
      <TextField
        fullWidth
        variant="outlined"
        multiline
        minRows={4}
        value={promptText}
        placeholder="Your prompt will appear here"
        InputProps={{
          readOnly: !isEditMode,
          endAdornment: isEditMode && (
            <InputAdornment position="end">
              <IconButton onClick={() => setManualPrompt(autoGeneratedPrompt)}>
                <ClearIcon />
              </IconButton>
            </InputAdornment>
          ),
        }}
        onChange={isEditMode ? (e) => setManualPrompt(e.target.value) : undefined} 
      />
    </Box>
  );
};

export default ArtTab;
