import React, { useState } from 'react';
import {
  Box,
  Tabs,
  Tab,
  TextField,
  Typography,
  Button,
  IconButton,
  InputAdornment,
} from '@mui/material';
import BackgroundTab from './BackgroundTab';
import CharacterTab from './CharacterTab';
import SpecialEffectsTab from './SpecialEffectsTab';
import ClearIcon from '@mui/icons-material/Clear';

const ArtTab = () => {
  const [subTabId, setSubTabId] = useState(0);
  const [isEditMode, setIsEditMode] = useState(false); // State for edit mode
  const [manualPrompt, setManualPrompt] = useState(''); // State for manually edited prompt
  const [hasManualPrompt, setHasManualPrompt] = useState(false);

  //PromptValues is the character object. could possibly still change the name to represent it better
  interface PromptValues {
    backgroundDescription: string;
    backgroundType: string;
    characterName: string;
    race: string;
    gender: string;
    age: string;
    charactertype: string;
    appearance: string;
    tool: string;
    inherited_tool: boolean;
    action: string;
    effect: string;
    sideCharacterName?: string;
    sideCharacterAppearance?: string;
    sideCharacterType?: string;
    sideCharacter2Name?: string;
    sideCharacter2Appearance?: string;
    sideCharacter2Type?: string;
  }

  const [promptValues, setPromptValues] = useState<PromptValues>({
    backgroundDescription: '',
    backgroundType: '',
    characterName: '',
    race: '',
    gender: '',
    age: '',
    charactertype: '',
    appearance: '',
    tool: '',
    inherited_tool: false,
    action: '',
    effect: '',
    sideCharacterName: '',
    sideCharacterAppearance: '',
    sideCharacterType: '',
    sideCharacter2Name: '',
    sideCharacter2Appearance: '',
    sideCharacter2Type: '',
  });

  const updatePromptValues = (newValues: Partial<typeof promptValues>) => {
    setPromptValues(prevValues => ({ ...prevValues, ...newValues }));
  };

  const handleSubTabChange = (
    _event: React.SyntheticEvent,
    newTabId: number
  ) => {
    setSubTabId(newTabId);
  };

  // Constructs the prompt
  const autoGeneratedPrompt = `Background: ${promptValues.backgroundDescription || 'N/A'}
  Type: ${promptValues.backgroundType || 'N/A'}
  Character: ${promptValues.characterName || 'N/A'}
  Race: ${promptValues.race || 'N/A'}
  Gender: ${promptValues.gender || 'N/A'}
  Age: ${promptValues.age || 'N/A'}
  Character Type: ${promptValues.charactertype || 'N/A'}
  Appearance: ${promptValues.appearance || 'N/A'}
  Tool: ${promptValues.tool || 'N/A'}
  Inherited Tool: ${promptValues.inherited_tool ? 'Yes' : 'No'} 
  Action: ${promptValues.action || 'N/A'}
  Effect: ${promptValues.effect || 'N/A'}
  Side Character: ${promptValues.sideCharacterName || 'N/A'}
  Side Character Appearance: ${promptValues.sideCharacterAppearance || 'N/A'}
  Side Character Type: ${promptValues.sideCharacterType || 'N/A'}
  Side Character 2: ${promptValues.sideCharacter2Name || 'N/A'}
  Side Character 2 Appearance: ${promptValues.sideCharacter2Appearance || 'N/A'}
  Side Character 2 Type: ${promptValues.sideCharacter2Type || 'N/A'}`;

  // The current prompt to display (either auto-generated or manually edited)
  const promptText =
    isEditMode && hasManualPrompt ? manualPrompt : autoGeneratedPrompt;

  // Toggle edit mode
  const toggleEditMode = () => {
    if (!isEditMode) {
      if (!hasManualPrompt) {
        setManualPrompt(autoGeneratedPrompt);
        setHasManualPrompt(true);
      }
    }
    setIsEditMode(!isEditMode);
  };

  return (
    <Box>
      <Tabs
        value={subTabId}
        onChange={handleSubTabChange}
        aria-label="art sub-tabs"
        sx={{ marginBottom: '1rem' }}
      >
        <Tab label="Background" />
        <Tab label="Character" />
        <Tab label="Special Effects" />
      </Tabs>

      {/* Display the relevant sub-tab */}
      <Box sx={{ display: subTabId === 0 ? 'block' : 'none' }}>
        <BackgroundTab updatePromptValues={updatePromptValues} />
      </Box>
      <Box sx={{ display: subTabId === 1 ? 'block' : 'none' }}>
        <CharacterTab updatePromptValues={updatePromptValues} />
      </Box>
      <Box sx={{ display: subTabId === 2 ? 'block' : 'none' }}>
        <SpecialEffectsTab updatePromptValues={updatePromptValues} />
      </Box>

      {/* Edit Mode Toggle Button */}
      <Box
        sx={{
          marginTop: '1.5rem',
          marginBottom: '1rem',
          display: 'flex',
          justifyContent: 'space-between',
        }}
      >
        <Typography variant="h6">Current Prompt</Typography>
        <Button
          onClick={toggleEditMode}
          variant="contained"
          color={isEditMode ? 'error' : 'primary'}
        >
          {isEditMode ? 'Edit Mode' : 'Auto generated'}
        </Button>
      </Box>

      {/* Prompt Display Box */}
      <TextField
        fullWidth
        variant="outlined"
        multiline
        minRows={4}
        value={promptText}
        placeholder="Your prompt will appear here"
        InputProps={{
          readOnly: !isEditMode,
          endAdornment: isEditMode && (
            <InputAdornment position="end">
              <IconButton onClick={() => setManualPrompt(autoGeneratedPrompt)}>
                <ClearIcon />
              </IconButton>
            </InputAdornment>
          ),
        }}
        onChange={isEditMode ? e => setManualPrompt(e.target.value) : undefined}
      />
    </Box>
  );
};

export default ArtTab;
