import { useRef, useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Tabs,
  Tab,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  FormControlLabel,
  Checkbox,
  IconButton,
  Typography
} from '@mui/material';
import SettingsIcon from '@mui/icons-material/Settings';
import HomeBar, { HomeBarRef } from '../../components/common/HomeBar';

interface ProcessManagementPageProps {
  refetch: () => Promise<void>;
}
  
const ProcessManagementPage = (props: ProcessManagementPageProps) => {
  const { refetch } = props;
  const homeBarRef = useRef<HomeBarRef>(null);
  const [tabId, setTabId] = useState<number>(0);

  const handleTabChange = (_event: React.SyntheticEvent, newTabId: number) => {
      setTabId(newTabId);
  };

  const tabColors = ['#14AE5C', '#E5A000', '#EC221F', '#5A5A5A'];
  // mock data
  const cardCounts = [12, 30, 3, 18];
  const tabLabels = ['Images Generated', 'Images in Queue', 'Images Failed', 'Prompt Missing or Incomplete'];

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        backgroundColor: '#244775',
        overflowX: 'hidden',
      }}
    >
      <Box sx={{ width: '100%', p: 2 }}>
        <HomeBar refetch={refetch} ref={homeBarRef} />
      </Box>

      <Box
        sx={{
          flex: 1,
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'center',
          overflow: 'auto',
        }}
      >
        <Card sx={{width: '90%'}}>
          <CardContent>
            <Tabs 
              value={tabId} 
              onChange={handleTabChange} 
              variant='fullWidth'
              textColor='inherit'
              TabIndicatorProps={{style: {backgroundColor: tabColors[tabId]}}}
            >
              {tabColors.map((color, index) => (
                <Tab
                  key={index}
                  label={
                    <Box>
                        <Typography variant='h2' sx={{ 
                          fontWeight: '500',
                          color: color, 
                          textAlign: 'center' 
                          }}
                        >
                          {cardCounts[index]}
                        </Typography>
                        <Typography sx={{ color: color }}>
                          {tabLabels[index]} 
                        </Typography>
                    </Box>
                  }
                />
              ))}
            </Tabs>

            <Box
              sx={{
                display: 'flex',
                gap: 2,
                m: 4
              }}
            >
              <FormControl fullWidth>
                <InputLabel>Created by</InputLabel>
                <Select>
                  <MenuItem>Pen name</MenuItem>
                </Select>
              </FormControl>
              <FormControl fullWidth>
                <InputLabel>Generated by</InputLabel>
                <Select>
                  <MenuItem>Username</MenuItem>
                </Select>
              </FormControl>
              <FormControl fullWidth>
                <InputLabel>Deck</InputLabel>
                <Select>
                  <MenuItem>-</MenuItem>
                </Select>
              </FormControl>
              <FormControl fullWidth>
                <InputLabel>Expansion</InputLabel>
                <Select>
                  <MenuItem>-</MenuItem>
                </Select>
              </FormControl>
              <FormControl fullWidth>
                <InputLabel>Generated since</InputLabel>
                <Select>
                  <MenuItem>Show all</MenuItem>
                </Select>
              </FormControl>

              <Box sx={{ display: 'flex', alignItems: 'center'}}>
                <FormControlLabel
                  control={
                      <Checkbox/>
                  }
                  label='Select all'
                  sx={{whiteSpace: 'nowrap'}}
                />
                <IconButton>
                  <SettingsIcon/>
                </IconButton> 
              </Box>              
            </Box>

            {tabId === 0 && (
              <Box m={2}>
                <p>Cards with images generated</p>
              </Box>
            )}
            {tabId === 1 && (
              <Box m={2}>
                <p>Cards with images in queue</p>
              </Box>
            )}
            {tabId === 2 && (
              <Box m={2}>
                <p>Cards with failed images</p>
              </Box>
            )}
            {tabId === 3 && (
              <Box m={2}>
                <p>Cards with missing or imcomplete prompt</p>
              </Box>
            )}
          </CardContent>
        </Card>
      </Box>
    </Box>
  );
};

export default ProcessManagementPage;
