/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Card_putCard"];
        post: operations["Card_postCard"];
        delete: operations["Card_deleteCard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/copy-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CopyCard_copyCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Image_postImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Role_putRole"];
        post: operations["Role_postRole"];
        delete: operations["Role_deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/role/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Role_getRole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Roles_listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/token-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TokenRequest_postTokenRequest"];
        delete: operations["TokenRequest_deleteTokenRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/token-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TokenRequests_listTokenRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["User_putUser"];
        post: operations["User_postUser"];
        delete: operations["User_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["User_getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card_links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description add card to deck */
        post: operations["CardLinks_createCardLink"];
        /** @description remove card from deck */
        delete: operations["CardLinks_deleteCardLink"];
        options?: never;
        head?: never;
        /** @description update count of cards in deck */
        patch: operations["CardLinks_updateCardLink"];
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description returns all decks user has access to */
        get: operations["Decks_listDecks"];
        put?: never;
        post: operations["Decks_createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deckId}/:copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description copies current deck with name '<deckname> (copy)' */
        post: operations["Decks_copyDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["Decks_updateDeck"];
        trace?: never;
    };
    "/user/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Authenticate_authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Cards_listCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChangePassword_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/expansions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Expansions_listExpansions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessRights: {
            isSuperAdmin?: boolean;
            canRelease?: boolean;
            canManageAdmins?: boolean;
            canManageUsers?: boolean;
            canClearContent?: boolean;
            hasUnlimitedTokens?: boolean;
            canShareTokens?: boolean;
            canMessageAdmins?: boolean;
            canMassExport?: boolean;
            canCreateContent?: boolean;
            canGenerateImages?: boolean;
            canMessage?: boolean;
            autoRefillTokens?: boolean;
            isRegularUser?: boolean;
            isPriorityUser?: boolean;
            isEmployee?: boolean;
            isContentCreator?: boolean;
        };
        Art: {
            prompt: string;
            manualPrompt: string;
            background: string;
            /** @enum {string} */
            type: "monster" | "backrow" | "spell" | "trap";
            characters: components["schemas"]["Character"][];
            specialEffects: string;
        };
        AuthenticateRequest: {
            username: string;
            password: string;
        };
        AuthenticateResponse: {
            authToken: string;
            /** Format: int32 */
            userId: number;
            firstname: string;
            lastname: string;
            accessRights: components["schemas"]["AccessRights"];
        };
        CardData: {
            /** Format: int32 */
            cardId: number;
            /** Format: int32 */
            ownerId: number;
            /** Format: int32 */
            errataOfId?: number;
            ownerFirstname: string;
            ownerLastname: string;
            cardName: string;
            isAce: boolean;
            cardClass: string;
            cardType: string;
            subtype: string;
            supertype: string;
            maximumPiece: string;
            secondaryClass: string;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            atk: number;
            /** Format: int32 */
            def: number;
            /** Format: int32 */
            primaryMaterialId?: number;
            /** Format: int32 */
            secondaryMaterialId?: number;
            /** Format: int32 */
            tertiaryMaterialId?: number;
            materialsReminder?: string;
            costText: string;
            effectText: string;
            flavourText: string;
            /** Format: int32 */
            countsAsId?: number;
            /** Format: float */
            artScale: number;
            /** Format: float */
            artXOffset: number;
            /** Format: float */
            artYOffset: number;
            /** Format: float */
            nameSize: number;
            /** Format: float */
            materialsSize: number;
            /** Format: float */
            effectsSize: number;
            /** Format: int32 */
            expansionId: number;
            /** Format: int32 */
            originalExpansionId: number;
            createdAt: string;
            updatedAt: string;
            cardEffects: components["schemas"]["CardEffects"];
            art: components["schemas"]["Art"];
            images: components["schemas"]["CardImage"][];
        };
        CardEffects: {
            cost: components["schemas"]["EffectsCost"];
            effect: components["schemas"]["EffectsEffect"];
        };
        CardExpansion: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            ownerId: number;
            name: string;
            /** Format: int32 */
            releaseYear: number;
            isReleased: boolean;
        };
        CardImage: {
            /**
             * Format: int32
             * @description use this id in backend to identify the generated assets
             */
            id: number;
            /** @enum {string} */
            status: "accepted" | "generated" | "queued" | "error";
            /** Format: int32 */
            generatedByUserId: number;
            generatedAt: string;
            art: components["schemas"]["Art"];
        };
        CardLink: {
            /** Format: int32 */
            deckId: number;
            /** Format: int32 */
            cardId: number;
            /** Format: int32 */
            count: number;
        };
        CardLinkUpdate: {
            /** Format: int32 */
            deckId?: number;
            /** Format: int32 */
            cardId?: number;
            /** Format: int32 */
            count?: number;
        };
        ChainEffect: {
            chainType: string;
            subtype: string | null;
            direction: string | null;
            /** Format: int32 */
            amount: number | null;
        };
        ChangePasswordRequest: {
            password: string;
        };
        ChangePasswordResponse: {
            status: string;
        };
        Character: {
            hidden: boolean;
            who: string;
            name: string;
            appearance: string;
            /** @enum {string} */
            race: "none" | "human" | "animal" | "beastial" | "monster" | "abstract";
            /** @enum {string} */
            gender: "none" | "undefined" | "female" | "male";
            /** @enum {string} */
            age: "none" | "adult" | "teen" | "elderly" | "child";
            /** @enum {string} */
            type: "main" | "supporting" | "antagonist" | "background";
            tool: string;
            action: string;
        };
        CopyCardRequest: {
            /** Format: int32 */
            cardId: number;
            serializedName: string;
            doErrata: boolean;
        };
        CopyCardResponse: {
            /** Format: int32 */
            cardId: number;
        };
        Deck: {
            /** Format: int32 */
            ownerId: number;
            /** Format: int32 */
            formatId: number;
            name: string;
            released: boolean;
            releasedAt: string | null;
            cardsLinks: components["schemas"]["CardLink"][];
        };
        DeckCreate: {
            name: string;
            released: boolean;
        };
        DeckList: {
            /** Format: int32 */
            countOfDecks: number;
            decks: components["schemas"]["Deck"][];
        };
        DeckUpdate: {
            name?: string;
            released?: boolean;
        };
        DeleteCardRequest: {
            /** Format: int32 */
            cardId: number;
        };
        DeleteCardResponse: {
            /** Format: int32 */
            cardId: number;
        };
        DeleteRoleRequest: {
            /** Format: int32 */
            roleId: number;
        };
        DeleteRoleResponse: {
            /** Format: int32 */
            roleId: number;
        };
        DeleteTokenRequestRequest: {
            /** Format: int32 */
            userId?: number;
        };
        DeleteTokenRequestResponse: {
            /** Format: int32 */
            userId: number;
        };
        DeleteUserRequest: {
            /** Format: int32 */
            userId: number;
            deleteAllTheirContent?: boolean;
        };
        DeleteUserResponse: {
            /** Format: int32 */
            userId: number;
        };
        EffectsCost: {
            prestate: string | null;
            costType: string;
            subtype: string | null;
            supertype: string | null;
            /** Format: int32 */
            amount: number | null;
            target: components["schemas"]["EffectsTarget"] | null;
            payment: components["schemas"]["EffectsPayment"] | null;
            postCount: components["schemas"]["PostCount"] | null;
        };
        EffectsCount: {
            /** Format: int32 */
            multiplier: number;
            target: components["schemas"]["EffectsTarget"] | null;
        };
        EffectsEffect: {
            effectType: string;
            subtype: string | null;
            supertype: string | null;
            amount: (number | components["schemas"]["EffectsCount"]) | null;
            /** Format: int32 */
            maxAmount: number | null;
            target: components["schemas"]["EffectsTarget"] | null;
            direction: string | null;
            hindrance: string | null;
            benefit: string | null;
            chainEffect: components["schemas"]["ChainEffect"] | null;
        };
        EffectsPayment: {
            paymentType: string | null;
            /** Format: int32 */
            amount: number | null;
            cardType: string | null;
        };
        EffectsTarget: {
            cardType: string | null;
            cardClass: string | null;
            subtype: string | null;
            /** Format: int32 */
            minLevel: number | null;
            /** Format: int32 */
            maxLevel: number | null;
            /** Format: int32 */
            atk: number | null;
            /** Format: int32 */
            def: number | null;
            zone: string | null;
            targetType: string | null;
            owner: string | null;
        };
        Error: {
            error: string;
        };
        ErrorForbidden: {
            error: string;
        };
        ErrorNotFound: {
            error: string;
        };
        ErrorUnauthorized: {
            error: string;
        };
        Format: {
            /** Format: int32 */
            id: number;
        };
        ListCardsResponse: {
            /** Format: int32 */
            countOfCards: number;
            cards: components["schemas"]["CardData"][];
        };
        ListExpansionsResponse: {
            /** Format: int32 */
            countOfExpansions: number;
            expansions: components["schemas"]["CardExpansion"][];
        };
        ListRolesResponse: {
            /** Format: int32 */
            countOfRoles: number;
            roles: components["schemas"]["UserRole"][];
        };
        ListTokenRequestsResponse: {
            /** Format: int32 */
            countOfTokenRequests: number;
            tokenRequests: components["schemas"]["UserTokenRequest"][];
        };
        ListUsersResponse: {
            /** Format: int32 */
            countOfUsers: number;
            users: components["schemas"]["SystemUser"][];
        };
        PostCardRequest: {
            cardName: string;
            serializedName: string;
            isAce: boolean;
            cardClass: string;
            cardType: string;
            subtype: string;
            supertype: string;
            maximumPiece: string;
            secondaryClass?: string;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            atk: number;
            /** Format: int32 */
            def: number;
            /** Format: int32 */
            primaryMaterialId: number | null;
            /** Format: int32 */
            secondaryMaterialId: number | null;
            /** Format: int32 */
            tertiaryMaterialId: number | null;
            materialsReminder: string;
            costText: string;
            effectText: string;
            flavourText: string;
            /** Format: int32 */
            countsAsId: number | null;
            /** Format: int32 */
            artScale: number;
            /** Format: int32 */
            artXOffset: number;
            /** Format: int32 */
            artYOffset: number;
            /** Format: int32 */
            nameSize: number;
            /** Format: int32 */
            materialsSize: number;
            /** Format: int32 */
            effectsSize: number;
            /** Format: int32 */
            expansionId: number;
            cardEffects: components["schemas"]["CardEffects"];
        };
        PostCardResponse: {
            /** Format: int32 */
            cardId: number;
        };
        PostCount: {
            countType: string;
            subtype: string | null;
        };
        PostImageRequest: {
            /** Format: int32 */
            cardId: number;
            /** Format: int32 */
            ownerId: number;
            imageName: string;
            /** Format: int32 */
            artScale: number;
            /** Format: int32 */
            artXOffset: number;
            /** Format: int32 */
            artYOffset: number;
            base64String: string;
        };
        PostImageResponse: {
            imagePath: string;
        };
        PostRoleRequest: {
            name: string;
            accessRights: components["schemas"]["AccessRights"];
        };
        PostRoleResponse: {
            /** Format: int32 */
            roleId: number;
        };
        PostTokenRequestRequest: {
            /** Format: int32 */
            userId?: number;
        };
        PostTokenRequestResponse: {
            /** Format: int32 */
            tokenRequestId: number;
        };
        PostUserRequest: {
            username: string;
            password: string;
            firstname: string;
            lastname: string;
            penName?: string;
            email?: string;
            phoneNumber?: string;
            isActive?: boolean;
            /** Format: int32 */
            roleId?: number;
            accessRights: components["schemas"]["AccessRights"];
        };
        PostUserResponse: {
            /** Format: int32 */
            userId: number;
        };
        PutCardRequest: {
            /** Format: int32 */
            cardId: number;
            cardName: string;
            serializedName: string;
            isAce: boolean;
            cardClass: string;
            cardType: string;
            subtype: string;
            supertype: string;
            maximumPiece: string;
            secondaryClass?: string;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            atk: number;
            /** Format: int32 */
            def: number;
            /** Format: int32 */
            primaryMaterialId: number | null;
            /** Format: int32 */
            secondaryMaterialId: number | null;
            /** Format: int32 */
            tertiaryMaterialId: number | null;
            materialsReminder: string;
            costText: string;
            effectText: string;
            flavourText: string;
            /** Format: int32 */
            countsAsId: number | null;
            /** Format: int32 */
            artScale: number;
            /** Format: int32 */
            artXOffset: number;
            /** Format: int32 */
            artYOffset: number;
            /** Format: int32 */
            nameSize: number;
            /** Format: int32 */
            materialsSize: number;
            /** Format: int32 */
            effectsSize: number;
            /** Format: int32 */
            expansionId: number;
            cardEffects: components["schemas"]["CardEffects"];
        };
        PutCardResponse: {
            /** Format: int32 */
            cardId: number;
        };
        PutRoleRequest: {
            /** Format: int32 */
            roleId: number;
            name: string;
            accessRights: components["schemas"]["AccessRights"];
        };
        PutRoleResponse: {
            /** Format: int32 */
            roleId: number;
        };
        PutUserRequest: {
            /** Format: int32 */
            userId: number;
            username: string;
            firstname: string;
            lastname: string;
            penName?: string;
            email?: string;
            phoneNumber?: string;
            isActive?: boolean;
            /** Format: int32 */
            roleId?: number;
            accessRights: components["schemas"]["AccessRights"];
        };
        PutUserResponse: {
            /** Format: int32 */
            userId: number;
        };
        SystemUser: {
            /** Format: int32 */
            id: number;
            username: string;
            firstname: string;
            lastname: string;
            penName?: string;
            email?: string;
            phoneNumber?: string;
            isActive: boolean;
            /** Format: int32 */
            roleId: number;
            accessRights: components["schemas"]["AccessRights"];
            tokenRequest?: components["schemas"]["UserTokenRequest"];
        };
        UserRole: {
            /** Format: int32 */
            id: number;
            name: string;
            accessRights: components["schemas"]["AccessRights"];
            createdAt: string;
            updatedAt: string;
        };
        UserTokenRequest: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            userId: number;
            /** Format: int32 */
            cardsInQueue: number;
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Card_putCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutCardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutCardResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Card_postCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostCardResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Card_deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteCardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCardResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    CopyCard_copyCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyCardRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopyCardResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Image_postImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostImageRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostImageResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Role_putRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRoleRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutRoleResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Role_postRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRoleRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRoleResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Role_deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRoleRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRoleResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Role_getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRole"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"] | components["schemas"]["ErrorNotFound"];
                };
            };
        };
    };
    Roles_listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRolesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    TokenRequest_postTokenRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostTokenRequestRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostTokenRequestResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"] | components["schemas"]["ErrorForbidden"];
                };
            };
        };
    };
    TokenRequest_deleteTokenRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteTokenRequestRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteTokenRequestResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    TokenRequests_listTokenRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTokenRequestsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    User_putUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutUserRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    User_postUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUserRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    User_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteUserRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteUserResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    User_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"] | components["schemas"]["ErrorNotFound"];
                };
            };
        };
    };
    Users_listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    CardLinks_createCardLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardLink"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardLink"];
                };
            };
        };
    };
    CardLinks_deleteCardLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    CardLinks_updateCardLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardLinkUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardLink"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Decks_listDecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckList"];
                };
            };
        };
    };
    Decks_createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
        };
    };
    Decks_copyDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deckId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Decks_updateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Authenticate_authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthenticateRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticateResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Cards_listCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCardsResponse"];
                };
            };
        };
    };
    ChangePassword_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorUnauthorized"];
                };
            };
        };
    };
    Expansions_listExpansions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExpansionsResponse"];
                };
            };
        };
    };
}
